FROM python:3.12-slim

WORKDIR /src

COPY src/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./src/pyproject.toml .

# dockerコンテキストで実行自体は./backend配下なのでこれでいいはず
COPY src/app ./app

WORKDIR  /src/app

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
